[package]
name = "one_model_acc"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
langchain-rust = { git = "https://github.com/Abraxas-365/langchain-rust" }